rancher/rancher-product-docs

versions/latest/modules/en/pages/cluster-admin/backups-and-restore/backups.adoc, versions/latest/modules/en/pages/cluster-admin/backups-and-restore/restore.adoc, versions/latest/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/latest/modules/en/pages/cluster-deployment/configuration/k3s.adoc, versions/latest/modules/en/pages/cluster-deployment/configuration/rke2.adoc, versions/latest/modules/en/pages/cluster-deployment/custom-clusters/windows/workload-migration-guidance.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/aws/aws.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/azure/azure.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/digitalocean/digitalocean.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/latest/modules/en/pages/cluster-deployment/set-up-cloud-providers/azure.adoc, versions/latest/modules/en/pages/installation-and-upgrade/install-rancher.adoc, versions/latest/modules/en/pages/installation-and-upgrade/installation-and-upgrade.adoc, versions/latest/modules/en/pages/installation-and-upgrade/other-installation-methods/air-gapped/infrastructure-private-registry.adoc, versions/latest/modules/en/pages/installation-and-upgrade/other-installation-methods/air-gapped/install-kubernetes.adoc, versions/latest/modules/en/pages/installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc, versions/latest/modules/en/pages/installation-and-upgrade/other-installation-methods/air-gapped/publish-images.adoc, versions/latest/modules/en/pages/installation-and-upgrade/other-installation-methods/http-proxy/install-kubernetes.adoc, versions/latest/modules/en/pages/installation-and-upgrade/quick-start/deploy-workloads/nodeports.adoc, versions/latest/modules/en/pages/installation-and-upgrade/quick-start/deploy-workloads/workload-ingress.adoc, versions/latest/modules/en/pages/installation-and-upgrade/resources/custom-ca-root-certificates.adoc, versions/latest/modules/en/pages/installation-and-upgrade/resources/upgrade-cert-manager.adoc, versions/latest/modules/en/pages/installation-and-upgrade/upgrades.adoc, versions/latest/modules/en/pages/observability/logging/enable-api-audit-log-in-downstream-clusters.adoc, versions/latest/modules/en/pages/observability/logging/enable-api-audit-log.adoc, versions/latest/modules/en/pages/observability/monitoring-and-dashboards/customizing-dashboard/create-persistent-grafana-dashboard.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/configure-azure-ad.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc, versions/latest/modules/en/pages/security/psact.adoc, versions/latest/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc
- Need to manually handle lines with multiple occurrences of angled bracket links
- Refs to removed files
=> Fix invalid refs

versions/latest/modules/en/pages/cluster-deployment/cluster-deployment.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/infra-providers.adoc, versions/latest/modules/en/pages/rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc, versions/latest/modules/en/pages/rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc, versions/latest/modules/zh/pages/cluster-deployment/cluster-deployment.adoc, versions/latest/modules/zh/pages/cluster-deployment/infra-providers/infra-providers.adoc, versions/latest/modules/zh/pages/rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc, versions/latest/modules/zh/pages/rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc, versions/v2.8/modules/en/pages/cluster-deployment/cluster-deployment.adoc, versions/v2.8/modules/en/pages/cluster-deployment/infra-providers/infra-providers.adoc, versions/v2.8/modules/en/pages/rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc, versions/v2.8/modules/en/pages/rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc, versions/v2.8/modules/zh/pages/cluster-deployment/cluster-deployment.adoc, versions/v2.8/modules/zh/pages/cluster-deployment/infra-providers/infra-providers.adoc, versions/v2.8/modules/zh/pages/rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc, versions/v2.8/modules/zh/pages/rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc, versions/v2.9/modules/en/pages/cluster-deployment/cluster-deployment.adoc, versions/v2.9/modules/en/pages/cluster-deployment/infra-providers/infra-providers.adoc, versions/v2.9/modules/en/pages/rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc, versions/v2.9/modules/en/pages/rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc, versions/v2.9/modules/zh/pages/cluster-deployment/cluster-deployment.adoc, versions/v2.9/modules/zh/pages/cluster-deployment/infra-providers/infra-providers.adoc, versions/v2.9/modules/zh/pages/rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc, versions/v2.9/modules/zh/pages/rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
Related to https://github.com/rancher/rancher-docs/issues/1516.
=> [SURE-9212] Use GitHub links for upstream Docker Machine docs (404s)

versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc, versions/v2.8/modules/en/pages/rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc, versions/v2.8/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc, versions/v2.9/modules/en/pages/rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc, versions/v2.9/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc
Related to https://github.com/rancher/rancher-docs/pull/827.
=> Sync PR#827 (Add client roles mapping section) from upstream

versions/latest/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc, versions/v2.8/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc, versions/v2.9/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc
Related to https://github.com/rancher/rancher-docs/pull/1528.
=> Sync PR#1528 ((re)document questions.yaml config values) from upstream

versions/latest/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/latest/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.8/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.8/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.9/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.9/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc
Related to https://github.com/rancher/rancher-docs/pull/1499.
=> Sync PR #1499 (Add manage-namespaces documentation) from upstream

versions/latest/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/latest/modules/en/pages/security/cves.adoc, versions/latest/modules/zh/pages/security/cves.adoc, versions/v2.8/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/v2.8/modules/en/pages/security/cves.adoc, versions/v2.8/modules/zh/pages/security/cves.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/v2.9/modules/en/pages/security/cves.adoc, versions/v2.9/modules/zh/pages/security/cves.adoc
Syncing product docs with community PR's:
https://github.com/rancher/rancher-docs/pull/1493
https://github.com/rancher/rancher-docs/pull/1502
https://github.com/rancher/rancher-docs/pull/1503
=> Sync Community PR 

versions/latest/modules/en/pages/security/security-overview.adoc, versions/latest/modules/zh/pages/security/security-overview.adoc, versions/v2.8/modules/en/pages/security/security-overview.adoc, versions/v2.8/modules/zh/pages/security/security-overview.adoc, versions/v2.9/modules/en/pages/security/security-overview.adoc, versions/v2.9/modules/zh/pages/security/security-overview.adoc
SURE-9375
Our supplemental bundle hard codes a bottom border that needed to be disabled and a top border added to match https://github.com/rancher/rancher-docs/blob/main/docs/reference-guides/rancher-security/rancher-security.md.
=> Fix raw HTML and update styling

versions/latest/modules/en/pages/installation-and-upgrade/resources/tls-secrets.adoc, versions/latest/modules/zh/pages/installation-and-upgrade/resources/tls-secrets.adoc, versions/v2.8/modules/en/pages/installation-and-upgrade/resources/tls-secrets.adoc, versions/v2.8/modules/zh/pages/installation-and-upgrade/resources/tls-secrets.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/resources/tls-secrets.adoc, versions/v2.9/modules/zh/pages/installation-and-upgrade/resources/tls-secrets.adoc
Related to https://github.com/rancher/rancher-docs/pull/1495
=> Sync PR #1495 (Update failing command on add-tls-secrets.md) from Community Docs

versions/latest/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/latest/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.8/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.8/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.9/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.9/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc
Related to https://github.com/rancher/rancher-docs/pull/1531
=> Sync PR #1531 (Improve encrypted backup docs) from Community Docs

versions/latest/modules/en/pages/api/workflows/projects.adoc, versions/latest/modules/zh/pages/api/workflows/projects.adoc, versions/v2.8/modules/en/pages/api/workflows/projects.adoc, versions/v2.8/modules/zh/pages/api/workflows/projects.adoc, versions/v2.9/modules/en/pages/api/workflows/projects.adoc, versions/v2.9/modules/zh/pages/api/workflows/projects.adoc
Related to https://github.com/rancher/rancher-docs/pull/1540
This PR only handles the changes to v2.8 and v2.9. The v2.10-specific update will need to be added at a later time when the 2.10 folder is created for this repo.
=> Sync PR #1540 (Document additional Project Public API workflows) from Community Docs

versions/latest/modules/en/pages/security/cves.adoc, versions/latest/modules/zh/pages/security/cves.adoc, versions/v2.8/modules/en/pages/security/cves.adoc, versions/v2.8/modules/zh/pages/security/cves.adoc, versions/v2.9/modules/en/pages/security/cves.adoc, versions/v2.9/modules/zh/pages/security/cves.adoc
Syncing CVE page with community PR 1583 and prior CVE's.
=> Syncing CVE Page

versions/latest/modules/en/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/latest/modules/zh/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/v2.10/modules/en/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/v2.10/modules/zh/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
Related to https://github.com/rancher/rancher-docs/pull/1432
=> Sync PR #1432 (Add docs for the new field RefreshInterval) from Community docs

versions/latest/modules/en/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/latest/modules/zh/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/v2.10/modules/en/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/v2.10/modules/zh/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
Related to https://github.com/rancher/rancher-docs/pull/1462
=> Sync PR #1462 (Add docs about enable/disable functionality in clusterrepo) from Community docs

shared/modules/ROOT/partials/en/configure-slo.adoc, shared/modules/ROOT/partials/zh/configure-slo.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/configure-keycloak-saml.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/configure-okta-saml.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/configure-pingidentity.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/microsoft-ad-federation-service-saml/rancher-for-ms-adfs.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/shibboleth-saml/shibboleth-saml.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-keycloak-saml.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-okta-saml.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-pingidentity.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/microsoft-ad-federation-service-saml/rancher-for-ms-adfs.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/shibboleth-saml/shibboleth-saml.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/configure-keycloak-saml.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/configure-okta-saml.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/configure-pingidentity.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/microsoft-ad-federation-service-saml/rancher-for-ms-adfs.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/shibboleth-saml/shibboleth-saml.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-keycloak-saml.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-okta-saml.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/configure-pingidentity.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/microsoft-ad-federation-service-saml/rancher-for-ms-adfs.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/shibboleth-saml/shibboleth-saml.adoc
Related to https://github.com/rancher/rancher-docs/pull/1335 and https://github.com/rancher/rancher-docs/pull/1550
=> Sync PR #1335 and #1550 (Update SAML Pages with SLO Feature) from Community docs

shared/modules/ROOT/partials/en/cluster-capabilities-table.adoc, shared/modules/ROOT/partials/zh/cluster-capabilities-table.adoc, versions/latest/modules/en/pages/cluster-deployment/register-existing-clusters.adoc, versions/latest/modules/en/pages/integrations/cluster-api/overview.adoc, versions/latest/modules/en/pages/observability/istio/istio.adoc, versions/latest/modules/zh/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc, versions/latest/modules/zh/pages/cluster-deployment/register-existing-clusters.adoc, versions/latest/modules/zh/pages/integrations/cluster-api/overview.adoc, versions/latest/modules/zh/pages/observability/istio/istio.adoc, versions/v2.10/modules/en/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.10/modules/en/pages/integrations/cluster-api/overview.adoc, versions/v2.10/modules/en/pages/observability/istio/istio.adoc, versions/v2.10/modules/zh/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc, versions/v2.10/modules/zh/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.10/modules/zh/pages/integrations/cluster-api/overview.adoc, versions/v2.10/modules/zh/pages/observability/istio/istio.adoc, versions/v2.8/modules/en/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.8/modules/en/pages/integrations/cluster-api/overview.adoc, versions/v2.8/modules/en/pages/observability/istio/istio.adoc, versions/v2.8/modules/zh/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.8/modules/zh/pages/integrations/cluster-api/overview.adoc, versions/v2.8/modules/zh/pages/observability/istio/istio.adoc, versions/v2.9/modules/en/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.9/modules/en/pages/integrations/cluster-api/overview.adoc, versions/v2.9/modules/en/pages/observability/istio/istio.adoc, versions/v2.9/modules/zh/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc, versions/v2.9/modules/zh/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.9/modules/zh/pages/integrations/cluster-api/overview.adoc, versions/v2.9/modules/zh/pages/observability/istio/istio.adoc
Fixes a handle of invalid ref errors. This PR brings the error log file size from 521 lines to 333 lines.
=> Fix invalid ref errors

playbook-local.yml
Forgot to turn search back on when it was disabled to speed up testing for https://github.com/rancher/rancher-product-docs/pull/127.
=> (re)enable search

versions/latest/modules/en/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/latest/modules/zh/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/v2.10/modules/en/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/v2.10/modules/zh/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/v2.8/modules/en/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/v2.8/modules/zh/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/v2.9/modules/en/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc, versions/v2.9/modules/zh/pages/cluster-deployment/hosted-kubernetes/eks/eks.adoc
Syncing the EKS page with community PR's across latest, v2.10, v2.9, and v2.8:
https://github.com/rancher/rancher-docs/pull/1585
https://github.com/rancher/rancher-docs/pull/1578
=> Sync EKS Page with Community Docs

versions/latest/modules/en/pages/security/cves.adoc, versions/latest/modules/zh/pages/security/cves.adoc, versions/v2.10/modules/en/pages/security/cves.adoc, versions/v2.10/modules/zh/pages/security/cves.adoc, versions/v2.8/modules/en/pages/security/cves.adoc, versions/v2.8/modules/zh/pages/security/cves.adoc, versions/v2.9/modules/en/pages/security/cves.adoc, versions/v2.9/modules/zh/pages/security/cves.adoc
Update CVE page for CVE-2024-52281 for:
Next:
=> Update CVE page for CVE-2024-52281

versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/v2.8/modules/en/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/v2.8/modules/zh/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/v2.9/modules/en/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc, versions/v2.9/modules/zh/pages/rancher-admin/users/authn-and-authz/authn-and-authz.adoc
Related to https://github.com/rancher/rancher-docs/pull/1635
Closes https://github.com/rancher/rancher-product-docs/issues/162
=> Sync PR #1635 from Community docs

versions/latest/modules/en/pages/cluster-deployment/set-up-cloud-providers/azure.adoc, versions/latest/modules/zh/pages/cluster-deployment/set-up-cloud-providers/azure.adoc, versions/v2.10/modules/en/pages/cluster-deployment/set-up-cloud-providers/azure.adoc, versions/v2.10/modules/zh/pages/cluster-deployment/set-up-cloud-providers/azure.adoc, versions/v2.9/modules/en/pages/cluster-deployment/set-up-cloud-providers/azure.adoc, versions/v2.9/modules/zh/pages/cluster-deployment/set-up-cloud-providers/azure.adoc
Related to https://github.com/rancher/rancher-docs/pull/1545
Closes https://github.com/rancher/rancher-product-docs/issues/163
=> Sync PR #1545 from Community docs

shared/modules/ROOT/partials/en/cni-popularity.adoc, shared/modules/ROOT/partials/zh/cni-popularity.adoc
Updating CNI stats for March 2025.
=> Updating CNI stats for March 2025.

versions/latest/modules/en/pages/observability/istio/istio.adoc, versions/v2.11/modules/en/pages/observability/istio/istio.adoc, versions/v2.11/modules/zh/pages/observability/istio/istio.adoc
Rancher-istio will be deprecated according to the following timeline:
- Rancher `2.11`: Deprecation announcement
- Rancher `2.12`: Deprecation configuration
- Rancher `2.13`: Removed
=> adding istio deprecation notice

versions/v2.10/modules/en/pages/faq/deprecated-features.adoc, versions/v2.10/modules/zh/pages/faq/deprecated-features.adoc
[2.10.4] Updating deprecated features date field.
=> [2.10.4] Updating Deprecated Features Date

versions/v2.9/modules/en/pages/faq/deprecated-features.adoc, versions/v2.9/modules/zh/pages/faq/deprecated-features.adoc
[2.9.8] Updating deprecated features date field.
=> [2.9.8] Updating Deprecated Features Date

versions/latest/modules/en/pages/faq/deprecated-features.adoc, versions/latest/modules/zh/pages/faq/deprecated-features.adoc, versions/v2.11/modules/en/pages/faq/deprecated-features.adoc, versions/v2.11/modules/zh/pages/faq/deprecated-features.adoc
[2.11.0] Updating Deprecated Features Date
=> [2.11.0] Updating Deprecated Features Date

versions/latest/modules/en/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/latest/modules/en/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc, versions/latest/modules/zh/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/latest/modules/zh/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc, versions/v2.11/modules/en/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/v2.11/modules/en/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc, versions/v2.11/modules/zh/pages/cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc, versions/v2.11/modules/zh/pages/cluster-admin/helm-charts-in-rancher/oci-repositories.adoc
Fixes https://github.com/rancher/rancher-product-docs/issues/215
=> Sync Community PR #1593 #1744 (Remove experimental banner for OCI)

versions/latest/modules/en/nav.adoc, versions/latest/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/latest/modules/en/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc, versions/latest/modules/zh/nav.adoc, versions/latest/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc, versions/latest/modules/zh/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc, versions/v2.11/modules/en/nav.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.11/modules/en/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc, versions/v2.11/modules/zh/nav.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.11/modules/zh/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc
=> Sync Community PR #1649 (Add documentation for aggregated clusterroles)

versions/latest/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/v2.10/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/v2.8/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc
=> Sync Community PR #1654 (nit: Update helm-cli.md)

versions/latest/modules/en/pages/security/psact.adoc, versions/latest/modules/zh/pages/security/psact.adoc, versions/v2.10/modules/en/pages/security/psact.adoc, versions/v2.10/modules/zh/pages/security/psact.adoc, versions/v2.11/modules/en/pages/security/psact.adoc, versions/v2.11/modules/zh/pages/security/psact.adoc, versions/v2.8/modules/en/pages/security/psact.adoc, versions/v2.8/modules/zh/pages/security/psact.adoc, versions/v2.9/modules/en/pages/security/psact.adoc, versions/v2.9/modules/zh/pages/security/psact.adoc
=> Sync Community PR #1704 ([v2.11] Policy Exemption User Note)

versions/latest/modules/en/nav.adoc, versions/latest/modules/en/pages/api/extension-apiserver.adoc, versions/latest/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/latest/modules/zh/nav.adoc, versions/latest/modules/zh/pages/api/extension-apiserver.adoc, versions/latest/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.11/modules/en/nav.adoc, versions/v2.11/modules/en/pages/api/extension-apiserver.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.11/modules/zh/nav.adoc, versions/v2.11/modules/zh/pages/api/extension-apiserver.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc
=> Syncing Community PR #1710 (Document extension APIserver)

versions/latest/modules/en/pages/cluster-deployment/register-existing-clusters.adoc, versions/latest/modules/zh/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.11/modules/en/pages/cluster-deployment/register-existing-clusters.adoc, versions/v2.11/modules/zh/pages/cluster-deployment/register-existing-clusters.adoc
Fixes #217 . Adjusted links to product docs as well.
=> Sync Community PR #1699 (New feature in 2.11: imported cluster version management)

versions/latest/modules/en/nav.adoc, versions/latest/modules/en/pages/cluster-deployment/enable-cluster-agent-scheduling-customization.adoc, versions/latest/modules/zh/nav.adoc, versions/latest/modules/zh/pages/cluster-deployment/enable-cluster-agent-scheduling-customization.adoc, versions/v2.11/modules/en/nav.adoc, versions/v2.11/modules/en/pages/cluster-deployment/enable-cluster-agent-scheduling-customization.adoc, versions/v2.11/modules/zh/nav.adoc, versions/v2.11/modules/zh/pages/cluster-deployment/enable-cluster-agent-scheduling-customization.adoc
=> Sync Community PR #1702 (New feature in 2.11: cluster agent scheduling customization)

versions/latest/modules/en/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/latest/modules/en/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/latest/modules/zh/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/latest/modules/zh/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.10/modules/en/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.10/modules/en/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.10/modules/zh/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.10/modules/zh/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.11/modules/en/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.11/modules/en/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.11/modules/zh/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.11/modules/zh/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.8/modules/en/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.8/modules/en/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.8/modules/zh/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.8/modules/zh/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.9/modules/en/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.9/modules/en/pages/troubleshooting/other-troubleshooting-tips/networking.adoc, versions/v2.9/modules/zh/pages/troubleshooting/other-troubleshooting-tips/dns.adoc, versions/v2.9/modules/zh/pages/troubleshooting/other-troubleshooting-tips/networking.adoc
=> Sync Community PR #1743 (Just a slightly better way to keep the container up)

versions/latest/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/latest/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.10/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.10/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/references/feature-flags.adoc, versions/v2.9/modules/zh/pages/installation-and-upgrade/references/feature-flags.adoc
=> Sync Community PR #1604 (Add note on the secret cleaner)

versions/latest/modules/en/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/latest/modules/zh/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.10/modules/en/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.10/modules/zh/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.11/modules/en/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.11/modules/zh/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.8/modules/en/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.8/modules/zh/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.9/modules/en/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc, versions/v2.9/modules/zh/pages/observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
=> Sync Community PR #1693 (Update servicemonitors and podmonitors spec links)

versions/latest/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/latest/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.10/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.10/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.11/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.11/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.8/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.8/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.9/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc, versions/v2.9/modules/zh/pages/rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
=> Sync Community PR #1639 (Add kubectl image for air-gapped environments)

versions/latest/modules/en/pages/cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc, versions/v2.10/modules/en/pages/cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc, versions/v2.11/modules/en/pages/cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc, versions/v2.8/modules/en/pages/cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc, versions/v2.9/modules/en/pages/cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc
=> Sync Community PR #1759 (Fix typo in in ingress-configuration)

versions/latest/modules/en/pages/cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc, versions/v2.10/modules/en/pages/cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc, versions/v2.11/modules/en/pages/cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc, versions/v2.8/modules/en/pages/cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc, versions/v2.9/modules/en/pages/cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc
=> Sync Community PR #1772 (Fix comma in authorized-cluster-endpoint)

versions/latest/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/usage-guide.adoc, versions/v2.10/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/usage-guide.adoc, versions/v2.11/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/usage-guide.adoc, versions/v2.8/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/usage-guide.adoc, versions/v2.9/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/usage-guide.adoc
=> Sync Community PR #1760 (Remove double word in back-up-restore-usage-guide)

versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/latest/modules/zh/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.10/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.10/modules/zh/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.11/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.11/modules/zh/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.8/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.8/modules/zh/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.9/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.9/modules/zh/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc
=> Sync Community PR #1584 PR #1777 (Clarify dependency)

versions/latest/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc, versions/v2.10/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc, versions/v2.11/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc, versions/v2.8/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc, versions/v2.9/modules/en/pages/cluster-admin/helm-charts-in-rancher/create-apps.adoc
=> Sync Community PR #1786 (fix: Misspelling)

versions/latest/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/latest/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.10/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.10/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.11/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.11/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.8/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.8/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.9/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.9/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc
Fixes #285 
The link has been updated to not point to our Community docs.
=> Sync Community PR #1375 (Update clean-cluster-nodes.md to point to RKE2 specific docs)

versions/latest/modules/en/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/latest/modules/en/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/latest/modules/en/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/latest/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/latest/modules/zh/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/latest/modules/zh/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.10/modules/en/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.10/modules/en/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.10/modules/en/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.10/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.10/modules/zh/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.10/modules/zh/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.11/modules/en/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.11/modules/en/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.11/modules/en/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.11/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.11/modules/zh/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.11/modules/zh/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.8/modules/en/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.8/modules/en/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.8/modules/en/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.8/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.8/modules/zh/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.8/modules/zh/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.9/modules/en/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.9/modules/en/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.9/modules/en/pages/cluster-admin/project-admin/add-users-to-projects.adoc, versions/v2.9/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc, versions/v2.9/modules/zh/pages/cluster-admin/manage-clusters/projects-and-namespaces.adoc, versions/v2.9/modules/zh/pages/cluster-admin/project-admin/add-users-to-projects.adoc
=>  Sync Community PR #1525 (Clarify how user search works)

versions/latest/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/latest/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.10/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.10/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.11/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.11/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.8/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.8/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.9/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.9/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc
=> Sync Community PR #1602 (Removing Incorrect Directories - [SURE-8597])

versions/latest/modules/en/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc, versions/latest/modules/zh/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc, versions/v2.11/modules/en/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc, versions/v2.11/modules/zh/pages/rancher-admin/experimental-features/cluster-role-aggregation.adoc
=> Sync Community PR #1825 (Update the version specified for Aggregated ClusterRole beta)

.github/ISSUE_TEMPLATE/release-maintenance-checklist.md
=> Sync Community PR #1850 (Add additional tasks to release checklist)

versions/latest/antora.yml, versions/v2.10/antora.yml, versions/v2.11/antora.yml, versions/v2.8/antora.yml, versions/v2.9/antora.yml
Update links to align with changes from https://github.com/rancher/longhorn-product-docs/pull/233.
=> Update SUSE Storage link format

versions/v2.10/modules/en/pages/faq/deprecated-features.adoc, versions/v2.10/modules/zh/pages/faq/deprecated-features.adoc
=> v2.10.8 Fix deprecated table

versions/latest/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/latest/modules/zh/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.10/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.10/modules/zh/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.8/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.8/modules/zh/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc, versions/v2.9/modules/zh/pages/installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc
Related to #137.
https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager has some content we might want to downstream?
=> Remove xref syntax from Quick Start

versions/latest/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc, versions/latest/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.10/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc, versions/v2.10/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.11/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc, versions/v2.11/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc, versions/v2.12/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc, versions/v2.12/modules/en/pages/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc
=> Sync Community PR #1603 (Detail resourceset usage in Backup docs)

versions/latest/modules/en/pages/security/secrets-hub.adoc, versions/v2.12/modules/en/pages/security/secrets-hub.adoc
=> Sync Community PR #1834 (Add new project scoped secret documentation)

versions/latest/modules/en/pages/contribute-to-rancher.adoc, versions/latest/modules/zh/pages/contribute-to-rancher.adoc, versions/v2.12/modules/en/pages/contribute-to-rancher.adoc, versions/v2.12/modules/zh/pages/contribute-to-rancher.adoc
=> Sync Community PR #1885 (Remove RKE1 references: contribute-to-rancher)

versions/latest/modules/en/nav.adoc, versions/latest/modules/en/pages/api/workflows/tokens.adoc, versions/latest/modules/zh/nav.adoc, versions/latest/modules/zh/pages/api/workflows/tokens.adoc, versions/v2.12/modules/en/nav.adoc, versions/v2.12/modules/en/pages/api/workflows/tokens.adoc, versions/v2.12/modules/zh/nav.adoc, versions/v2.12/modules/zh/pages/api/workflows/tokens.adoc
=> Sync Community PR #1839 (Add Tokens example workflows page)

versions/latest/modules/en/pages/api/extension-apiserver.adoc, versions/latest/modules/en/pages/installation-and-upgrade/requirements/requirements.adoc, versions/v2.12/modules/en/pages/api/extension-apiserver.adoc, versions/v2.12/modules/en/pages/installation-and-upgrade/requirements/requirements.adoc
Fixes https://github.com/rancher/rancher-product-docs/issues/380 and https://github.com/rancher/rancher-product-docs/issues/406
=> Sync Community PR #1948 (add aggregation layer configuration required) and PR #1852 (Require API Aggregation)

versions/latest/modules/en/pages/cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc, versions/latest/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc, versions/v2.12/modules/en/pages/cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc, versions/v2.12/modules/zh/pages/cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
=>  Sync Community PR #1930 (Remove RKE1 references: use-kubectl-and-kubeconfig

versions/latest/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/latest/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.12/modules/en/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc, versions/v2.12/modules/zh/pages/cluster-admin/manage-clusters/clean-cluster-nodes.adoc
=> Sync Community PR #1992 (Remove RKE1 references: clean cluster nodes)

versions/latest/modules/en/pages/cluster-deployment/infra-providers/aws/aws.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/azure/azure.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/digitalocean/digitalocean.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/gce/gce.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/nutanix/nutanix.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-credentials.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/shutdown-vm.adoc, versions/latest/modules/en/pages/cluster-deployment/infra-providers/vsphere/vsphere.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/aws/aws.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/azure/azure.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/digitalocean/digitalocean.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/gce/gce.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/nutanix/nutanix.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-a-vm-template.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/vsphere/create-credentials.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/vsphere/shutdown-vm.adoc, versions/v2.12/modules/en/pages/cluster-deployment/infra-providers/vsphere/vsphere.adoc
Fixes #371 
Note, GCE updates aren't included as it's dependent on https://github.com/rancher/rancher-product-docs/issues/350 to introduce the file.
=> Sync Community PR #1924 (Remove RKE1 references: use-new-nodes-in-an-infra-provider/<providers>)

shared/modules/ROOT/partials/en/api-support-warning.adoc, shared/modules/ROOT/partials/zh/api-support-warning.adoc, versions/latest/modules/en/pages/api/v3-rancher-api-guide.adoc, versions/latest/modules/zh/pages/api/v3-rancher-api-guide.adoc, versions/v2.10/modules/en/pages/api/v3-rancher-api-guide.adoc, versions/v2.10/modules/zh/pages/api/v3-rancher-api-guide.adoc, versions/v2.11/modules/en/pages/api/v3-rancher-api-guide.adoc, versions/v2.11/modules/zh/pages/api/v3-rancher-api-guide.adoc, versions/v2.12/modules/en/pages/api/v3-rancher-api-guide.adoc, versions/v2.12/modules/zh/pages/api/v3-rancher-api-guide.adoc, versions/v2.8/modules/en/pages/api/v3-rancher-api-guide.adoc, versions/v2.8/modules/zh/pages/api/v3-rancher-api-guide.adoc, versions/v2.9/modules/en/pages/api/v3-rancher-api-guide.adoc, versions/v2.9/modules/zh/pages/api/v3-rancher-api-guide.adoc
Updating the v3 API page with a warning and added partial to contain warning messaging. Also updated phrasing in intro paragraph.
=> Update v3 API Page

shared/modules/ROOT/partials/en/rollback-warning.adoc, shared/modules/ROOT/partials/zh/rollback-warning.adoc, versions/latest/modules/en/pages/installation-and-upgrade/rollbacks.adoc, versions/latest/modules/zh/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.10/modules/en/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.10/modules/zh/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.12/modules/en/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.12/modules/zh/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.8/modules/en/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.8/modules/zh/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/rollbacks.adoc, versions/v2.9/modules/zh/pages/installation-and-upgrade/rollbacks.adoc
Updating partial section with rollback warning, and removing EOL version information from rollback pages.
Tied to https://github.com/rancher/rancher-product-docs/issues/309
=> Updating Rollback Pages

shared/modules/ROOT/partials/en/permissions-warning.adoc, shared/modules/ROOT/partials/zh/permissions-warning.adoc, versions/latest/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/latest/modules/zh/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.10/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.10/modules/zh/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.11/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.11/modules/zh/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.12/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.12/modules/zh/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.8/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.8/modules/zh/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.9/modules/en/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc, versions/v2.9/modules/zh/pages/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
Adding warning note to Global Permissions page for users with permissions to modify accounts or resources.
Related to https://github.com/rancher/rancher-docs/pull/2005
=> Update Global Permissions Page - Trusted Users Warning Note

versions/v2.11/modules/en/pages/faq/deprecated-features.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.11/modules/en/pages/release-notes.adoc, versions/v2.11/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.11/modules/zh/pages/faq/deprecated-features.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.11/modules/zh/pages/release-notes.adoc, versions/v2.11/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc
=> v2.11.6 Maintenance Tasks

versions/v2.10/modules/en/pages/faq/deprecated-features.adoc, versions/v2.10/modules/en/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.10/modules/en/pages/release-notes.adoc, versions/v2.10/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.10/modules/zh/pages/faq/deprecated-features.adoc, versions/v2.10/modules/zh/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.10/modules/zh/pages/release-notes.adoc, versions/v2.10/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc
=> v2.10.10 Maintenance Tasks

versions/v2.11/modules/en/pages/faq/deprecated-features.adoc, versions/v2.11/modules/en/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.11/modules/en/pages/release-notes.adoc, versions/v2.11/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.11/modules/zh/pages/faq/deprecated-features.adoc, versions/v2.11/modules/zh/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.11/modules/zh/pages/release-notes.adoc, versions/v2.11/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc
=> Merge v2.11.6 into main

versions/v2.9/modules/en/pages/faq/deprecated-features.adoc, versions/v2.9/modules/en/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.9/modules/en/pages/release-notes.adoc, versions/v2.9/modules/en/pages/security/rancher-webhook/rancher-webhook.adoc, versions/v2.9/modules/zh/pages/faq/deprecated-features.adoc, versions/v2.9/modules/zh/pages/installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc, versions/v2.9/modules/zh/pages/release-notes.adoc, versions/v2.9/modules/zh/pages/security/rancher-webhook/rancher-webhook.adoc
=> Merge v2.9.12 into main

versions/latest/antora.yml, versions/v2.10/antora.yml, versions/v2.11/antora.yml, versions/v2.12/antora.yml, versions/v2.8/antora.yml, versions/v2.9/antora.yml
Attributes available via product-docs-common/global-attributes.yml now
=> Remove unneeded component attributes

versions/latest/modules/en/pages/rancher-admin/experimental-features/rancher-on-arm64.adoc, versions/latest/modules/zh/pages/rancher-admin/experimental-features/rancher-on-arm64.adoc, versions/v2.12/modules/en/pages/rancher-admin/experimental-features/rancher-on-arm64.adoc, versions/v2.12/modules/zh/pages/rancher-admin/experimental-features/rancher-on-arm64.adoc
Syncing with [community PR #1940](https://github.com/rancher/rancher-docs/pull/1940), updating rancher-on-arm64.adoc for latest/v2.12.
=> Syncing Community PR #1940

versions/latest/modules/en/pages/rancher-admin/global-configuration/ui-server-side-pagination.adoc, versions/latest/modules/zh/pages/rancher-admin/global-configuration/ui-server-side-pagination.adoc, versions/v2.12/modules/en/pages/rancher-admin/global-configuration/ui-server-side-pagination.adoc, versions/v2.12/modules/zh/pages/rancher-admin/global-configuration/ui-server-side-pagination.adoc
=> Sync Community PR #2004 (Ensure list of UI limitations with vai/server-side pagination enabled is correct)

.github/workflows/test-deploy.yml
Attempt to fix permission issue
=> Permission fix
